{"name": "test_successful_auth_and_token_usage", "status": "failed", "statusDetails": {"message": "AssertionError: Не удалось получить доступ с токеном\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": "tests/api/test_login_token.py:49: in test_successful_auth_and_token_usage\n    assert profile_response.status_code == 200, \"Не удалось получить доступ с токеном\"\nE   AssertionError: Не удалось получить доступ с токеном\nE   assert 404 == 200\nE    +  where 404 = <Response [404]>.status_code"}, "start": 1745166938730, "stop": 1745166939636, "uuid": "c476cbd1-0aec-4cca-8a4f-36308dc6fe45", "historyId": "9832d042f1b1a9b8d065980084a1d460", "testCaseId": "9832d042f1b1a9b8d065980084a1d460", "fullName": "tests.api.test_login_token#test_successful_auth_and_token_usage", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_login_token"}, {"name": "host", "value": "MacBook-Pro-macbook.local"}, {"name": "thread", "value": "85207-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_login_token"}]}